# Generated by Django 5.0.1 on 2025-11-20 11:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descricao', models.TextField(blank=True)),
                ('tipo_dado', models.CharField(choices=[('decimal', 'Decimal'), ('integer', 'Inteiro'), ('text', 'Texto'), ('boolean', 'Booleano')], default='text', max_length=20)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
                'ordering': ['chave'],
            },
        ),
        migrations.CreateModel(
            name='Textura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Textura',
                'verbose_name_plural': 'Texturas',
                'ordering': ['ordem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('codigo_calc', models.IntegerField(help_text='Código usado nos cálculos (baseado no comprimento do nome)')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Corte',
                'verbose_name_plural': 'Tipos de Corte',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Material',
                'verbose_name_plural': 'Tipos de Material',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ValorCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('canvas', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=10)),
                ('cetim', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=10)),
            ],
            options={
                'verbose_name': 'Valor de Corte',
                'verbose_name_plural': 'Valores de Corte',
                'ordering': ['largura'],
            },
        ),
        migrations.CreateModel(
            name='ValorGoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('goma_fino', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=10)),
                ('goma_grosso', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=10)),
                ('termocolante', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=10)),
            ],
            options={
                'verbose_name': 'Valor de Goma',
                'verbose_name_plural': 'Valores de Goma',
                'ordering': ['largura'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(blank=True, help_text='000.000.000-00', max_length=14)),
                ('data_admissao', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=Decimal('5.0'), help_text='Percentual de comissão sobre vendas', max_digits=5)),
                ('meta_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Meta de vendas mensal em R$', max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('tipo_cliente', models.CharField(choices=[('industria_novo', 'Indústria Novo'), ('industria_antigo', 'Indústria Antigo'), ('comercio_novo', 'Comércio Novo'), ('comercio_antigo', 'Comércio Antigo')], default='comercio_novo', max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=300)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('numero_pedido', models.CharField(blank=True, max_length=50)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('data_previsao_entrega', models.DateField(blank=True, null=True)),
                ('largura_mm', models.IntegerField(help_text='Largura em mm', validators=[django.core.validators.MinValueValidator(1)])),
                ('comprimento_mm', models.IntegerField(help_text='Comprimento em mm', validators=[django.core.validators.MinValueValidator(1)])),
                ('cor_urdume', models.CharField(choices=[('branco', 'Branco'), ('preto', 'Preto'), ('branco_preto', 'Branco e Preto'), ('vermelho', 'Vermelho'), ('nenhum', 'Nenhum')], default='nenhum', max_length=20)),
                ('quantidade_metros', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantidade_unidades', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unidades_por_pacote', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('tem_goma', models.BooleanField(default=False)),
                ('tipo_goma', models.CharField(blank=True, choices=[('fino', 'Fino'), ('grosso', 'Grosso'), ('termo', 'Termocolante')], max_length=20)),
                ('tem_ultrassonico', models.BooleanField(default=False)),
                ('valor_metro', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=10)),
                ('valor_milheiro', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('valor_unidade', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_corte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orcamento.tipocorte')),
                ('tipo_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orcamento.tipomaterial')),
                ('vendedor', models.ForeignKey(blank=True, help_text='Vendedor responsável pelo orçamento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='orcamento.vendedor')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-data_emissao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metragem', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('preco_metro', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tipo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='orcamento.tipomaterial')),
            ],
            options={
                'verbose_name': 'Tabela de Preço',
                'verbose_name_plural': 'Tabelas de Preços',
                'ordering': ['metragem', 'tipo_material'],
                'unique_together': {('metragem', 'tipo_material')},
            },
        ),
        migrations.CreateModel(
            name='CoeficienteFator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura', models.IntegerField(help_text='Largura em mm', validators=[django.core.validators.MinValueValidator(1)])),
                ('coeficiente', models.DecimalField(decimal_places=5, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('codigo_corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coeficientes', to='orcamento.tipocorte')),
                ('tipo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coeficientes', to='orcamento.tipomaterial')),
            ],
            options={
                'verbose_name': 'Coeficiente Fator',
                'verbose_name_plural': 'Coeficientes Fator',
                'ordering': ['largura', 'tipo_material'],
                'unique_together': {('largura', 'tipo_material', 'codigo_corte')},
            },
        ),
    ]
