# Generated by Django 5.0.1 on 2025-11-20 12:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='milheiros',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Milheiros - CALCULADO = ARREDONDAR.PARA.BAIXO(Unidades/1000,2)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='quantidade_metros',
            field=models.IntegerField(help_text='Metros - DIGITADO pelo usuário', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='quantidade_unidades',
            field=models.IntegerField(help_text='Unidades - CALCULADO automaticamente', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
