# Generated by Django 5.0.1 on 2025-11-20 13:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0002_orcamento_milheiros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.CharField(choices=[('Fd', 'Fundo (Fd)'), ('1', '1ª'), ('2', '2ª'), ('3', '3ª'), ('4', '4ª'), ('5', '5ª'), ('6', '6ª'), ('7', '7ª')], default='Fd', max_length=2)),
                ('densidade', models.CharField(choices=[('1', '1ª Densidade'), ('2', '2ª Densidade')], default='1', help_text='1ª ou 2ª densidade (apenas para Dupla Densidade)', max_length=1)),
                ('codigo_cor', models.CharField(help_text='Ex: F01, T30, etc', max_length=20)),
                ('quantidade_unidades', models.IntegerField(help_text='Quantas unidades desta cor', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantidade_demais', models.IntegerField(default=0, help_text="Coluna '+ Demais' (opcional)", validators=[django.core.validators.MinValueValidator(0)])),
                ('ordem', models.IntegerField(default=0)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cores', to='orcamento.orcamento')),
            ],
            options={
                'verbose_name': 'Cor do Orçamento',
                'verbose_name_plural': 'Cores do Orçamento',
                'ordering': ['orcamento', 'densidade', 'ordem', 'posicao'],
                'unique_together': {('orcamento', 'posicao', 'densidade')},
            },
        ),
    ]
