# Generated by Django 5.0.1 on 2025-11-20 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0003_cororcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='quantidade_unidades',
            field=models.IntegerField(default=1, help_text='Unidades - CALCULADO automaticamente', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
