# Generated by Django 5.0.1 on 2025-11-20 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0004_alter_orcamento_quantidade_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomaterial',
            name='batidas',
            field=models.IntegerField(default=20, help_text='Número de batidas para este material (1ª densidade ou densidade única)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='tipomaterial',
            name='batidas_2densidade',
            field=models.IntegerField(blank=True, help_text='Número de batidas para 2ª densidade (apenas para materiais de dupla densidade)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
