# Generated by Django 5.0.1 on 2025-11-20 14:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0005_tipomaterial_batidas_tipomaterial_batidas_2densidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipomaterial',
            name='batidas',
        ),
        migrations.RemoveField(
            model_name='tipomaterial',
            name='batidas_2densidade',
        ),
        migrations.CreateModel(
            name='Batida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_batidas', models.IntegerField(help_text='Número de batidas (ex: 20, 25, 28)', validators=[django.core.validators.MinValueValidator(1)])),
                ('descricao', models.CharField(blank=True, help_text="Descrição adicional (ex: '20 batidas', '28 batidas')", max_length=100)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_material', models.ForeignKey(help_text='Material ao qual esta opção de batida pertence', on_delete=django.db.models.deletion.CASCADE, related_name='batidas', to='orcamento.tipomaterial')),
            ],
            options={
                'verbose_name': 'Batida',
                'verbose_name_plural': 'Batidas',
                'ordering': ['tipo_material', 'ordem', 'numero_batidas'],
                'unique_together': {('tipo_material', 'numero_batidas')},
            },
        ),
        migrations.AddField(
            model_name='orcamento',
            name='batida',
            field=models.ForeignKey(blank=True, help_text='Número de batidas selecionado para este material', null=True, on_delete=django.db.models.deletion.PROTECT, to='orcamento.batida'),
        ),
    ]
