# Generated by Django 5.0.1 on 2025-11-20 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0006_remove_tipomaterial_batidas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura_mm', models.IntegerField(help_text='Largura da fita em mm', unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('fator', models.DecimalField(decimal_places=2, help_text='Fator de conversão/rendimento associado à largura', max_digits=10)),
            ],
            options={
                'verbose_name': 'Fita (Fator)',
                'verbose_name_plural': 'Fitas (Fatores)',
                'ordering': ['largura_mm'],
            },
        ),
    ]
