# Generated by Django 5.0.1 on 2025-11-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0007_fita'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='tabela_manual_metragem',
            field=models.IntegerField(blank=True, choices=[(300, '300 m'), (500, '500 m'), (1000, '1.000 m'), (2500, '2.500 m'), (5000, '5.000 m'), (10000, '10.000 m'), (15000, '15.000 m')], help_text='Override manual da faixa de metragem (Planilha T11). Se vazio, usa a metragem digitada.', null=True),
        ),
    ]
