# Generated by Django 5.0.1 on 2025-11-22 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0008_orcamento_tabela_manual_metragem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='textura',
            field=models.ForeignKey(blank=True, help_text='Textura selecionada para a etiqueta', null=True, on_delete=django.db.models.deletion.PROTECT, to='orcamento.textura'),
        ),
    ]
