# Generated by Django 5.0.1 on 2025-11-22 11:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0009_orcamento_textura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acabamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Acabamento / Material',
                'verbose_name_plural': 'Acabamentos / Materiais',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='tem_goma',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='tipo_goma',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='acabamento',
            field=models.ForeignKey(blank=True, help_text='Material / Acabamento selecionado (ex: Goma, Termocolante)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orcamento.acabamento'),
        ),
        migrations.CreateModel(
            name='PrecoAcabamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura_mm', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('preco', models.DecimalField(decimal_places=5, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='orcamento.acabamento')),
            ],
            options={
                'verbose_name': 'Preço de Acabamento',
                'verbose_name_plural': 'Preços de Acabamentos',
                'ordering': ['largura_mm', 'acabamento'],
                'unique_together': {('largura_mm', 'acabamento')},
            },
        ),
    ]
