# Generated by Django 5.0.1 on 2025-11-26 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0010_acabamento_remove_orcamento_tem_goma_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('digitando', 'Digitando'), ('aguardando', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('em_producao', 'Em Produção'), ('finalizado', 'Finalizado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='digitando', help_text='Status atual do fluxo do orçamento', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricoStatusOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, choices=[('digitando', 'Digitando'), ('aguardando', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('em_producao', 'Em Produção'), ('finalizado', 'Finalizado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], max_length=20, null=True)),
                ('novo_status', models.CharField(choices=[('digitando', 'Digitando'), ('aguardando', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('em_producao', 'Em Produção'), ('finalizado', 'Finalizado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], max_length=20)),
                ('data_mudanca', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, help_text='Motivo da mudança (opcional)')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='orcamento.orcamento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['-data_mudanca'],
            },
        ),
    ]
