# Generated by Django 5.0.1 on 2025-12-02 17:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0011_orcamento_status_historicostatusorcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='batida',
            name='fator',
            field=models.DecimalField(decimal_places=5, default=Decimal('1.0'), help_text='Fator usado no cálculo para esta combinação de Material + Batidas', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
