# Generated by Django 5.0.1 on 2025-12-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0012_batida_fator'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomaterial',
            name='dupla_densidade',
            field=models.BooleanField(default=False, help_text='Indica se este material é do tipo Dupla Densidade'),
        ),
    ]
